#!/bin/sh

if [ ! -d /userdata/system/configs/drastic ];then
	mkdir -p /userdata/system/configs/drastic
	cp -r /usr/share/drastic/* /userdata/system/configs/drastic/
fi

cd /userdata/system/configs/drastic

SDL_GAMECONTROLLERCONFIG='19000000010000000100000000010000,RG35XX Gamepad,a:b0,b:b1,x:b2,y:b3,leftshoulder:b4,rightshoulder:b5,lefttrigger:b6,righttrigger:b7,guide:b8,start:b9,back:b10,dpup:b13,dpleft:b15,dpright:b16,dpdown:b14,volumedown:b11,volumeup:b12,platform:Linux' drastic "$1"

