#!/bin/sh

#SDL_VSYNC=1 SDL_GAMECONTROLLERCONFIG="19000000010000000100000000010000,RG35XX Gamepad,platform:Linux,b:b0,a:b1,dpdown:h0.4,lefttrigger:a2,dpleft:h0.8,rightshoulder:b5,leftshoulder:b4,righttrigger:a5,dpright:h0.2,back:b7,start:b8,dpup:h0.1,y:b2,x:b3,guide:b9," SDL_RENDER_DRIVER=opengles2 PPSSPP "$1"
SDL_VSYNC=1 SDL_RENDER_DRIVER=opengles2 PPSSPP "$1"

